cafeteria/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView

from canteen import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin/", admin.site.urls),
    path("canteen/", include("canteen.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("images/favicon.ico")),
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canteen/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView

app_name = "canteen"
urlpatterns = [
    path("cart/", views.cart, name="cart"),
    path("menu/", views.menu, name="menu"),
    path("contact/", views.contact, name="contact"),
    path("help/", views.help, name="help"),
    path("sub_menu/<str:menu_type>/", views.sub_menu, name="sub_menu"),
    path("checkout/", views.checkout, name="checkout"),
    path("update_item/", views.updateItem, name="update_item"),
    path("process_order/", views.process_order, name="process_order"),
    path("reservations/", views.ReservationListView.as_view(), name="reservations"),
    path("reserve_seat/", views.ReservationCreateView.as_view(), name="reserve_seat"),
    path(
        "update_reservation/<int:pk>/<str:type>",
        views.update_reservation,
        name="update_reservation",
    ),
    # path("help/", TemplateView.as_view(template_name="canteen/help.html"), name="help"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("confirmation/", views.confirmation, name="confirmation"),
    path(
        "activate/<uidb64>/<token>/", views.ActivateAccount.as_view(), name="activate"
    ),
]

canteen/models.py
from django.contrib.auth.models import User
# from django_resized import ResizedImageField
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _


def validate_cellphone(value):
    """
    Validate whether the cellphone number is a valid MTC/TN number
    """
    # print(F"VALUE: {value}")
    if len(value) < 10:
        raise ValidationError(
            _(f"Cellphone number must have 10 digits."),
            params={"value": value},
        )
    elif value[:3] not in ["081", "085"]:
        raise ValidationError(
            _(f"A valid cellphone number must start with '081' or '085'"),
            params={"value": value},
        )
    for digit in value:
        if digit not in "0123456789":
            raise ValidationError(
                _(f"Cellphone number must contain digits only."),
                params={"value": value},
            )


def minimum_qantity(value):
    """
    Validate that quantity of an order item is not < 1
    """
    # print(F"VALUE: {value}")
    if value < 1:
        raise ValidationError(
            _(f"You cannot add an item with 0 quantity."),
            params={"value": value},
        )


class Customer(models.Model):
    customer = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE, related_name="customer"
    )

    def __str__(self):
        return f"{self.customer.username}"


class Table(models.Model):
    table_number = models.IntegerField(unique=True, blank=False, null=False, default=0)
    max_seats = models.IntegerField(blank=False, null=False, default=0)
    description = models.CharField(blank=True, null=True, max_length=250)
    # empty_seats = models.IntegerField()

    def __str__(self):
        return f"{self.table_number}"


class Seat(models.Model):
    SEAT_STATUS = [
        ("OPEN", "Open"),
        ("PENDING", "Pending"),
        ("RESERVED", "Reserved"),
    ]
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    seat_number = models.IntegerField(unique=True, blank=False, null=False)
    status = models.CharField(
        max_length=8, choices=SEAT_STATUS, editable=False, default="OPEN"
    )

    def clean(self):
        selected_table = Table.objects.get(id=self.table.id)
        number_of_seats = Seat.objects.filter(table=self.table.id).count()
        print(f"SELECTED_TABLE: {selected_table}")
        print(f"MAX_SEATS: {selected_table.max_seats}")
        print(f"NUMBER_OF_SEATS: {number_of_seats}")
        if not self.id:
            if number_of_seats >= selected_table.max_seats:
                raise ValidationError(
                    {
                        "table": _(
                            f"Table {selected_table.table_number} has reached maximum seats."
                        )
                    }
                )

    def __str__(self):
        return f"{self.seat_number}"


class Reservation(models.Model):
    RESERVATION_STATUS = [
        ("PENDING", "Pending"),
        ("ACCEPTED", "Accepted"),
        ("DECLINED", "Declined"),
        ("EXPIRED", "Expired"),
    ]
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="reservations"
    )
    seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=8, choices=RESERVATION_STATUS, default="PENDING"
    )
    time_reserved = models.DateTimeField(auto_now_add=True)

    def clean(self):
        selected_seat = Seat.objects.get(id=self.seat.id)
        print(f"SELECTED_SEAT: {selected_seat}")
        active_reservations = Reservation.objects.filter(
            Q(status="PENDING") | Q(status="ACCEPTED")
        ).select_related("customer")
        print(f"ACTIVE RESERVATIONS: {active_reservations}")
        reservists = [reservation.customer for reservation in active_reservations]
        active_reservation_ids = [reservation.id for reservation in active_reservations]
        print(f"RESERVISTS: {reservists}")
        if selected_seat.status in ["PENDING", "RESERVED"]:
            if not self.id:  # New record
                raise ValidationError(
                    {"seat": _("The selected seat is already reserved.")}
                )  # The seat you want is already reserved || remove this by showing open seats only
            else:
                if self.id not in active_reservation_ids and self.status in [
                    "PENDING",
                    "ACCEPTED",
                ]:
                    raise ValidationError(
                        {"seat": _("The selected seat is already reserved.")}
                    )
        if self.customer in reservists:
            if not self.id:  # New record
                raise ValidationError(
                    {"customer": _("The customer already has an active reservation.")}
                )  # You already have a pending resevation || remove this by disabling reservation when already waiting
            else:
                if self.id not in active_reservation_ids and self.status in [
                    "PENDING",
                    "ACCEPTED",
                ]:
                    raise ValidationError(
                        {
                            "customer": _(
                                "The customer already has an active reservation."
                            )
                        }
                    )
        super(Reservation, self).clean()

    def __str__(self):
        return f"{self.id}"


class Product(models.Model):
    PRODUCT_TYPES = [
        ("MEAL", "Meal"),
        ("FOOD", "Food"),
        ("DRINK", "Drink"),
        ("FRUIT", "Fruit"),
        ("SNACK", "Snack"),
        ("DESSERT", "Dessert"),
    ]
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    product_type = models.CharField(max_length=7, choices=PRODUCT_TYPES)
    price = models.FloatField()
    image = models.ImageField(
        default="product_pics/placeholder.png", upload_to="product_pics"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["name", "description", "product_type"],
                name="unique_products",
            )
        ]

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url


class Order(models.Model):
    ORDER_STATUS = [
        ("OPEN", "Open"),
        ("SUBMITTED", "Submitted"),
        ("CANCELLED", "Cancelled"),
        ("COMPLETED", "Completed"),
    ]

    PAYMENT_METHOD = [
        ("", "Select a Payment Method"),
        ("PAYPAL", "PayPal"),
        ("CREDIT_OR_DEBIT CARD", "Credit/Debit Card"),
        ("EFT", "EFT"),
        ("EWALLET", "eWallet"),
        ("EASYWALLET", "EasyWallet"),
        ("BLUEWALLET", "BlueWallet"),
        ("CASH", "Cash"),
    ]
    customer = models.ForeignKey(
        Customer,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    date_ordered = models.DateTimeField(auto_now_add=True)
    delivery = models.BooleanField(default=False)
    submitted = models.BooleanField(default=False)
    reference = models.CharField(max_length=100, null=True, blank=True, help_text="Payment reference number for EFT and Wallets. For wallets, send payment to 0810000000. EFT should be made to US Cafeteria, FNB Current Acc. 62000000000, Branch Code 58117.")
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD)
    status = models.CharField(max_length=9, choices=ORDER_STATUS, default="OPEN")
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    def clean(self):
        if not self.id:
            active_orders = Order.objects.filter(submitted=False)
            print(f"ACTIVE ORDERS: {active_orders}")
            active_orderers = [order.customer for order in active_orders]
            print(f"ORDERERS: {active_orderers}")
            print(f"THIS ORDERER: {self.customer}")
            if self.customer in active_orderers:
                raise ValidationError(
                    {"customer": _("This customer already has an open order.")}
                )

    @property
    def get_cart_total(self):
        order_items = self.order_items.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_items(self):
        order_items = self.order_items.all()
        total = sum([item.quantity for item in order_items])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, null=True, related_name="order_items"
    )
    quantity = models.IntegerField(null=True, blank=True, default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "product",
                    "order",
                ],
                name="unique_order_items",
            )
        ]

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class DeliveryAddress(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, related_name="address"
    )
    # order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name="Delivery Address",
        help_text="Enter your delivery address on campus, e.g., office No. & office location",
    )
    date_added = models.DateTimeField(auto_now_add=True)

canteen/forms.py
from unicodedata import name

from django import forms
from pyexpat import model
from users.models import Profile

from .models import Customer, DeliveryAddress, Order, Reservation, Seat


class AddressUpdateForm(forms.ModelForm):
    class Meta:
        model = DeliveryAddress
        fields = ["address"]
        widgets = {
            "address": forms.TextInput(
                attrs={
                    "class": "form-control form-control-lg mb-2",
                    "name": "address",
                    "required": True,                 
                }
            )
        }

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["cellphone"]
        widgets = {
            "cellphone": forms.TextInput(
                attrs={
                    "class": "form-control form-control-lg mb-2",
                    "required":True,
                }
            )
        }


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["payment_method", "delivery", "reference"]
        widgets = {
            "delivery": forms.CheckboxInput(
                attrs={
                    "type": "checkbox",
                    "class": "form-check mb-2",
                    "name": "delivery",
                    "id": "delivery",
                }
            ),
            "payment_method": forms.Select(
                attrs={
                    "class": "form-control form-control-lg mb-2",
                    "id": "paymentMethod",
                    "required":True
                }
            ),
            "reference": forms.TextInput(
                attrs={
                    "class": "form-control form-control-lg mb-2", 
                    "disabled": "disabled",
                    "id": "reference",
                    "required":True,
                }
            ),
        }
        


class ReservationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["customer"].disabled = True

    class Meta:
        model = Reservation
        fields = ["customer", "seat"]

    customer = forms.ModelChoiceField(
        queryset=Customer.objects.all(),
        empty_label="Select customer",
        widget=forms.Select(attrs={"class": "form-control form-control-lg mb-2"}),
    )

    seat = forms.ModelChoiceField(
        queryset=Seat.objects.filter(status="OPEN").order_by("seat_number"),
        empty_label="Select the seat",
        widget=forms.Select(attrs={"class": "form-control form-control-lg mb-2"}),
    )

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True, widget=forms.TextInput(attrs={"class": "form-control form-control-lg mb-2"}))
    subject = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "form-control form-control-lg mb-2"}))
    message = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control form-control-lg mb-2"}), required=True)

canteen/templates/canteen/help.html
{% extends 'canteen/main.html' %} {% load static %} {% block welcome %}
<h1>Help Centre</h1>
<hr />
<h4>
  <em
    >Read the instructions and guidelines below to better understand how this
    platform works.</em
  >
</h4>
<!-- <hr> -->
{% endblock %} {% block content %}
<div class="container block-content">
  <div class="accordion" id="accordionExample">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h2 class="mb-0">
          <button
            class="btn btn-link btn-block text-left"
            type="button"
            data-toggle="collapse"
            data-target="#collapseOne"
            aria-expanded="true"
            aria-controls="collapseOne"
          >
            General Guidelines
          </button>
        </h2>
      </div>
      <div
        id="collapseOne"
        class="collapse show"
        aria-labelledby="headingOne"
        data-parent="#accordionExample"
      >
        <div class="card-body">
          <h4>What it's about</h4>
          <p>
            This web application provides a platform for our customers to
            interact with us online. The platform is aimed to enhance
            convenience to our clients by allowing them to place orders as well
            as reserve seats in the cafeteria from the comfort of their office,
            home or elsewhere. This reduces frustration from queues while
            improving efficiency and time management.
          </p>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingTwo">
        <h2 class="mb-0">
          <button
            class="btn btn-link btn-block text-left collapsed"
            type="button"
            data-toggle="collapse"
            data-target="#collapseTwo"
            aria-expanded="false"
            aria-controls="collapseTwo"
          >
            User Registration
          </button>
        </h2>
      </div>
      <div
        id="collapseTwo"
        class="collapse"
        aria-labelledby="headingTwo"
        data-parent="#accordionExample"
      >
        <div class="card-body">
          <h4>Cafeteria Staff Registration</h4>
          <p>
            The canteen staff responsible for processing customer orders need to
            be registered and granted with <em>Staff</em> permission by the
            Admin. NB: Staff user accounts do not have permission to make seat
            reservations
          </p>
          <h4>Customer Registration</h4>
          <p>
            Only logged in customers can place orders and reserve seats online.
            A customer can create a personal user account by navigating to
            <a href="{% url 'users:register' %}">Register.</a>
            Once an account is created, an activation request is sent to the
            Admin. The user can only login to their acount after it has been
            activated by the Admin. Once the account is activated, the user will
            be notified via email. Upon activation, the user can login to their
            account and update their profile with an image, a
            residential/delivery address and a cellphone number (to be used for
            SMS notification).
          </p>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingThree">
        <h2 class="mb-0">
          <button
            class="btn btn-link btn-block text-left collapsed"
            type="button"
            data-toggle="collapse"
            data-target="#collapseThree"
            aria-expanded="false"
            aria-controls="collapseThree"
          >
            Seat Reservation
          </button>
        </h2>
      </div>
      <div
        id="collapseThree"
        class="collapse"
        aria-labelledby="headingThree"
        data-parent="#accordionExample"
      >
        <div class="card-body">
          <p>
            A logged in customer can reserve one of the open seats in the
            cafeteria. Once a reservation is made, it will be added to the list
            of active reservations, but with the Status of <em>Pending</em>. A
            notification is sent to staff emails to either accept or decline the
            reservation. (A confirmation of the reservation is also sent to the
            customer via email and SMS if there's a cellphone number on the
            customer's profile.) Once the reservation has been
            accepted/declined, another notification will be sent to the customer
            via email and SMS. Reservations will be updated to
            <em>Expired</em> status by the staff after it has been used. (An
            update is being developed to automate this process based on time
            intervals.) The customer can cancel their own reservation at any
            time from the Reservations list page.
          </p>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingFour">
        <h2 class="mb-0">
          <button
            class="btn btn-link btn-block text-left collapsed"
            type="button"
            data-toggle="collapse"
            data-target="#collapseFour"
            aria-expanded="false"
            aria-controls="collapseFour"
          >
            Online Orders
          </button>
        </h2>
      </div>
      <div
        id="collapseFour"
        class="collapse"
        aria-labelledby="headingThree"
        data-parent="#accordionExample"
      >
        <div class="card-body">
          <p>
            Customers can place their orders online with or without delivery
            option. When an order with no delivery is done, the customer will be
            informed through the phone number on their profile. Customers can
            use any of the payment methods availabel at checkout page, which
            include the integrated PayPal or Debit/Credit card. Customer using
            non-integrated methods such as EFT and cellphone banking must
            include the payment reference number when submitting the order as no
            order will be prepared without confirmation that a payment was made.
          </p>
        </div>
      </div>
    </div>
  </div>
  <br /><br />
  <h5 style="text-align: center">
    Still have some questions?
    <a href="{% url 'canteen:contact' %}">Contact us here</a> or via our
    contacts on the footer.
  </h5>
</div>
{% endblock %}

canteen/templates/canteen/list_view.html
{% extends 'canteen/main.html' %} {% load static %} {% block welcome %}
<h1>{{ heading }}</h1>
<hr />
{% endblock %} {% block content %}
<div class="container block-content">
<br />
<h4>
  Number of Open Seats: <span class="badge badge-info">{{ open_seats}}</span>
</h4>
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Customer</th>
      <th scope="col">Seat</th>
      <th scope="col">Status</th>
      <th scope="col">Time Reserved</th>
      {% if user.is_staff %}
      <th scope="col">Accept</th>
      <th scope="col">Decline</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for reservation in reservation_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>
        {{reservation.customer}} 
        {% if user.customer.id == reservation.customer.id %}
        <a
          class="btn btn-outline-danger ml-3"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='cancel' %}"
          role="button"
          >Cancel</a
        >
        {% endif %}
      </td>
      <td>{{reservation.seat}}</td>
      <td>{{reservation.status}}</td>
      <td>{{reservation.time_reserved}}</td>
      {% if user.is_staff %}
      <td>
        {% if reservation.status == "PENDING" %}
        <a
          class="btn btn-outline-success"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='accept' %}"
          role="button"
          >Accept</a
        >
        {% else %}
        <button type="button" class="btn btn-outline-secondary" disabled>
          Accept
        </button>
        {% endif %}
      </td>
      <td>
        {% if reservation.status == "PENDING" %}
        <a
          class="btn btn-outline-danger"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='decline' %}"
          role="button"
          >Decline</a
        >
        {% else %}
        <button type="button" class="btn btn-outline-secondary" disabled>
          Decline
        </button>
        {% endif %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if is_paginated %}
<div class="pagination pagination-lg justify-content-center">
  <span class="page-link">
    <!-- step-link from django change to page-link  bootstrap class -->
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endif %} {% if user.is_staff %}
<button type="button" class="btn btn-secondary btn-lg btn-block" disabled>
  Please process the pending reservations.
</button>
{% elif open_seats == 0 %}
<button type="button" class="btn btn-secondary btn-lg btn-block" disabled>
  There are currently no open seats. Please, check again later.
</button>
{% else %}
<a
  class="btn btn-outline-primary btn-lg btn-block"
  href="{% url 'canteen:reserve_seat' %}"
  role="button"
  >Make a Reservation</a
>
{% endif %} 
</div>
{% endblock content %}

canteen/templates/canteen/menu.html
{% extends 'canteen/main.html' %}
{% load static %}
{% block welcome %}
<h3>Our Menus</h3>
<hr>
{% endblock %}
{% block content %}
<div class="container block-content">
<div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-4">
      <div class="card">
        <img src="{% static 'images/meals.jpg' %}" class="card-img-top" alt="Main Meal Image">
        <div class="card-body">
          <h5 class="card-title">Main Meals</h5>
          <a
            class="btn btn-outline-primary btn-lg"
            href="{% url 'canteen:sub_menu' 'meal' %}"
            role="button"
            >View Meals</a
            >
        </div>
      </div>
    </div>
    <div class="col mb-4">
      <div class="card">
        <img src="{% static 'images/eggs.jpg' %}" class="card-img-top" alt="Extras Image">
        <div class="card-body">
          <h5 class="card-title">Extras/Sides</h5>
          <a
            class="btn btn-outline-primary btn-lg"
            href="{% url 'canteen:sub_menu' 'food' %}"
            role="button"
            >View Extras</a
            >
        </div>
      </div>
    </div>
    <div class="col mb-4">
      <div class="card">
        <img src="{% static 'images/dessert.jpg' %}" class="card-img-top" alt="Desserts Image">
        <div class="card-body">
          <h5 class="card-title">Desserts</h5>
          <a
            class="btn btn-outline-primary btn-lg"
            href="{% url 'canteen:sub_menu' 'dessert' %}"
            role="button"
            >View Desserts</a
            >
        </div>
      </div>
    </div>
    <div class="col mb-4">
      <div class="card">
        <img src="{% static 'images/snacks.jpg' %}" class="card-img-top" alt="Snacks Image">
        <div class="card-body">
          <h5 class="card-title">Snacks</h5>
          <a
            class="btn btn-outline-primary btn-lg"
            href="{% url 'canteen:sub_menu' 'snack' %}"
            role="button"
            >View Snacks</a
            >
        </div>
      </div>
    </div>
    <div class="col mb-4">
        <div class="card">
          <img src="{% static 'images/fruits.jpg' %}" class="card-img-top" alt="Fruits Image">
          <div class="card-body">
            <h5 class="card-title">Fruits</h5>
            <a
              class="btn btn-outline-primary btn-lg"
              href="{% url 'canteen:sub_menu' 'fruit' %}"
              role="button"
              >View Fruits</a
              >
          </div>
        </div>
      </div>
      <div class="col mb-4">
        <div class="card">
          <img src="{% static 'images/beverages.jpg' %}" class="card-img-top" alt="Beverages Image">
          <div class="card-body">
            <h5 class="card-title">Beverages</h5>
            <a
              class="btn btn-outline-primary btn-lg"
              href="{% url 'canteen:sub_menu' 'drink' %}"
              role="button"
              >View Beverages</a
              >
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock content %}

canteen/templates/canteen/reservation_list.html
{% extends 'canteen/main.html' %} {% load static %} {% block welcome %}
<h1>{{ heading }}</h1>
<hr />
{% endblock %} {% block content %}
<div class="container block-content">
<br />
<h4>
  Number of Open Seats: <span class="badge badge-info">{{ open_seats}}</span>
</h4>
<table class="table table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Customer</th>
      <th scope="col">Seat Number</th>
      <th scope="col">Reservation Status</th>
      <th scope="col">Time Reserved</th>
      {% if user.is_staff %}
      <th scope="col">Accept</th>
      <th scope="col">Decline</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for reservation in reservation_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>
        {{reservation.customer}} 
        {% if user.customer.id == reservation.customer.id %}
        <a
          class="btn btn-outline-danger ml-3"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='cancel' %}"
          role="button"
          >Cancel</a
        >
        {% endif %}
      </td>
      <td>{{reservation.seat}}</td>
      <td>{{reservation.status}}</td>
      <td>{{reservation.time_reserved}}</td>
      {% if user.is_staff %}
      <td>
        {% if reservation.status == "PENDING" %}
        <a
          class="btn btn-outline-success"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='accept' %}"
          role="button"
          >Accept</a
        >
        {% else %}
        <button type="button" class="btn btn-outline-secondary" disabled>
          Accept
        </button>
        {% endif %}
      </td>
      <td>
        {% if reservation.status == "PENDING" %}
        <a
          class="btn btn-outline-danger"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='decline' %}"
          role="button"
          >Decline</a
        >
        {% elif reservation.status == "ACCEPTED" %}
        <a
          class="btn btn-outline-danger"
          href="{% url 'canteen:update_reservation' pk=reservation.id type='expire' %}"
          role="button"
          >Expire</a
        >
        {% else %}
        <button type="button" class="btn btn-outline-secondary" disabled>
          Decline
        </button>
        {% endif %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if is_paginated %}
<div class="pagination pagination-lg justify-content-center">
  <span class="page-link">
    <!-- step-link from django change to page-link  bootstrap class -->
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endif %} {% if user.is_staff %}
<button type="button" class="btn btn-secondary btn-lg btn-block" disabled>
  Please process the pending reservations.
</button>
{% elif open_seats == 0 %}
<button type="button" class="btn btn-secondary btn-lg btn-block" disabled>
  There are currently no open seats. Please, check again later.
</button>
{% else %}
<a
  class="btn btn-outline-primary btn-lg btn-block"
  href="{% url 'canteen:reserve_seat' %}"
  role="button"
  >Make a Reservation</a
>
{% endif %} 
</div>
{% endblock content %}